### ISSUE TITLE
Error: spawnSync ./gradlew EACCES

### ISSUE THREAD

**Issue by utsavtiwary04** [EkaanshArora/Agora-React-Native-Demo#4]
Thanks a lot for helping out with react-native and Agora. I am facing the following issue after executing the **react-native run-android** command - 

`error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: spawnSync ./gradlew EACCES
    at Object.spawnSync (internal/child_process.js:1046:20)
    at spawnSync (child_process.js:595:24)
    at execFileSync (child_process.js:622:15)`

**Comment by utsavtiwary04** [comment]
Solved using `chmod 755 android/gradlew`
